// FIFA World Cup curiosities used as fill-in-the-blank grammar exercises.
// Each entry targets the grammar point for its topic:
//   Present Simple vs Continuous   → answer is conjugated verb OR "is/are + -ing"
//   Present Perfect vs Past Simple → answer is "has/have" OR past verb alone
//   Present Perfect vs Perfect Continuous → answer is "has" (PP) OR "has been" (PPC)
//   Will vs Going to               → answer is "will" OR "is/are going to"
//   Mixed Review                   → any of the above

export const CURIOSITIES = [

  // ─────────────────────────────────────────────────────────────
  // PRESENT SIMPLE VS CONTINUOUS
  // ─────────────────────────────────────────────────────────────
  {
    id: 1,
    topic: 'Present Simple vs Continuous',
    country: 'Brazil',
    template: 'Brazil always ___ in every World Cup.',
    answer: 'participates',
    tense: 'present-simple',
    fullSentence: 'Brazil always participates in every World Cup.',
  },
  {
    id: 2,
    topic: 'Present Simple vs Continuous',
    country: 'Germany',
    template: 'Germany ___ football with great discipline.',
    answer: 'plays',
    tense: 'present-simple',
    fullSentence: 'Germany plays football with great discipline.',
  },
  {
    id: 3,
    topic: 'Present Simple vs Continuous',
    country: 'Argentina',
    template: 'Argentina ___ hard for the 2026 title right now.',
    answer: 'is training',
    tense: 'present-continuous',
    fullSentence: 'Argentina is training hard for the 2026 title right now.',
  },
  {
    id: 4,
    topic: 'Present Simple vs Continuous',
    country: 'Mexico',
    template: 'Mexico ___ passionate fans to every match.',
    answer: 'attracts',
    tense: 'present-simple',
    fullSentence: 'Mexico attracts passionate fans to every match.',
  },
  {
    id: 5,
    topic: 'Present Simple vs Continuous',
    country: 'France',
    template: 'France ___ a new golden generation currently.',
    answer: 'is building',
    tense: 'present-continuous',
    fullSentence: 'France is building a new golden generation currently.',
  },
  {
    id: 6,
    topic: 'Present Simple vs Continuous',
    country: 'Spain',
    template: 'Spain traditionally ___ possession-style football.',
    answer: 'plays',
    tense: 'present-simple',
    fullSentence: 'Spain traditionally plays possession-style football.',
  },
  {
    id: 7,
    topic: 'Present Simple vs Continuous',
    country: 'Japan',
    template: 'Japan ___ its national squad for 2026 right now.',
    answer: 'is preparing',
    tense: 'present-continuous',
    fullSentence: 'Japan is preparing its national squad for 2026 right now.',
  },
  {
    id: 8,
    topic: 'Present Simple vs Continuous',
    country: 'England',
    template: 'England usually ___ well under high pressure.',
    answer: 'performs',
    tense: 'present-simple',
    fullSentence: 'England usually performs well under high pressure.',
  },
  {
    id: 9,
    topic: 'Present Simple vs Continuous',
    country: 'Morocco',
    template: 'Morocco ___ African football on the world stage.',
    answer: 'represents',
    tense: 'present-simple',
    fullSentence: 'Morocco represents African football on the world stage.',
  },
  {
    id: 10,
    topic: 'Present Simple vs Continuous',
    country: 'USA',
    template: 'The USA ___ its stadiums for the 2026 cup now.',
    answer: 'is upgrading',
    tense: 'present-continuous',
    fullSentence: 'The USA is upgrading its stadiums for the 2026 cup now.',
  },
  {
    id: 11,
    topic: 'Present Simple vs Continuous',
    country: 'Uruguay',
    template: 'Uruguay always ___ a strong defensive style.',
    answer: 'uses',
    tense: 'present-simple',
    fullSentence: 'Uruguay always uses a strong defensive style.',
  },
  {
    id: 12,
    topic: 'Present Simple vs Continuous',
    country: 'Croatia',
    template: 'Croatia ___ young talent for 2026 right now.',
    answer: 'is developing',
    tense: 'present-continuous',
    fullSentence: 'Croatia is developing young talent for 2026 right now.',
  },

  // ─────────────────────────────────────────────────────────────
  // PRESENT PERFECT VS PAST SIMPLE
  // ─────────────────────────────────────────────────────────────
  {
    id: 13,
    topic: 'Present Perfect vs Past Simple',
    country: 'Brazil',
    template: 'Brazil ___ won the World Cup five times.',
    answer: 'has',
    tense: 'present-perfect',
    fullSentence: 'Brazil has won the World Cup five times.',
  },
  {
    id: 14,
    topic: 'Present Perfect vs Past Simple',
    country: 'Germany',
    template: 'Germany ___ the World Cup in Brazil in 2014.',
    answer: 'won',
    tense: 'past-simple',
    fullSentence: 'Germany won the World Cup in Brazil in 2014.',
  },
  {
    id: 15,
    topic: 'Present Perfect vs Past Simple',
    country: 'Argentina',
    template: 'Argentina ___ the World Cup in Qatar in 2022.',
    answer: 'won',
    tense: 'past-simple',
    fullSentence: 'Argentina won the World Cup in Qatar in 2022.',
  },
  {
    id: 16,
    topic: 'Present Perfect vs Past Simple',
    country: 'France',
    template: 'France ___ won two World Cups so far.',
    answer: 'has',
    tense: 'present-perfect',
    fullSentence: 'France has won two World Cups so far.',
  },
  {
    id: 17,
    topic: 'Present Perfect vs Past Simple',
    country: 'England',
    template: 'England ___ won the World Cup only once in history.',
    answer: 'has',
    tense: 'present-perfect',
    fullSentence: 'England has won the World Cup only once in history.',
  },
  {
    id: 18,
    topic: 'Present Perfect vs Past Simple',
    country: 'Spain',
    template: 'Spain ___ the 2010 final against Netherlands.',
    answer: 'won',
    tense: 'past-simple',
    fullSentence: 'Spain won the 2010 final against Netherlands.',
  },
  {
    id: 19,
    topic: 'Present Perfect vs Past Simple',
    country: 'Italy',
    template: 'Italy ___ not qualified for the last two cups.',
    answer: 'has',
    tense: 'present-perfect',
    fullSentence: 'Italy has not qualified for the last two cups.',
  },
  {
    id: 20,
    topic: 'Present Perfect vs Past Simple',
    country: 'Uruguay',
    template: 'Uruguay ___ the very first World Cup in 1930.',
    answer: 'hosted',
    tense: 'past-simple',
    fullSentence: 'Uruguay hosted the very first World Cup in 1930.',
  },
  {
    id: 21,
    topic: 'Present Perfect vs Past Simple',
    country: 'Netherlands',
    template: 'Netherlands ___ reached three World Cup finals.',
    answer: 'has',
    tense: 'present-perfect',
    fullSentence: 'Netherlands has reached three World Cup finals.',
  },
  {
    id: 22,
    topic: 'Present Perfect vs Past Simple',
    country: 'Japan',
    template: 'Japan ___ the Round of 16 in Qatar 2022.',
    answer: 'reached',
    tense: 'past-simple',
    fullSentence: 'Japan reached the Round of 16 in Qatar 2022.',
  },
  {
    id: 23,
    topic: 'Present Perfect vs Past Simple',
    country: 'Croatia',
    template: 'Croatia ___ finished third in 2018 and 2022.',
    answer: 'has',
    tense: 'present-perfect',
    fullSentence: 'Croatia has finished third in 2018 and 2022.',
  },
  {
    id: 24,
    topic: 'Present Perfect vs Past Simple',
    country: 'South Korea',
    template: 'South Korea ___ the semifinals in 2002.',
    answer: 'reached',
    tense: 'past-simple',
    fullSentence: 'South Korea reached the semifinals in 2002.',
  },

  // ─────────────────────────────────────────────────────────────
  // PRESENT PERFECT VS PERFECT CONTINUOUS
  //   PP  → blank is "has"       (has + past participle already shown)
  //   PPC → blank is "has been"  (has been + -ing already shown)
  // ─────────────────────────────────────────────────────────────
  {
    id: 25,
    topic: 'Present Perfect vs Perfect Continuous',
    country: 'Brazil',
    template: 'Brazil ___ competed in all 22 World Cups.',
    answer: 'has',
    tense: 'present-perfect',
    fullSentence: 'Brazil has competed in all 22 World Cups.',
  },
  {
    id: 26,
    topic: 'Present Perfect vs Perfect Continuous',
    country: 'Germany',
    template: 'Germany ___ rebuilding since the 2018 group exit.',
    answer: 'has been',
    tense: 'present-perfect-continuous',
    fullSentence: 'Germany has been rebuilding since the 2018 group exit.',
  },
  {
    id: 27,
    topic: 'Present Perfect vs Perfect Continuous',
    country: 'Argentina',
    template: 'Argentina ___ improving since the 2014 final.',
    answer: 'has been',
    tense: 'present-perfect-continuous',
    fullSentence: 'Argentina has been improving since the 2014 final.',
  },
  {
    id: 28,
    topic: 'Present Perfect vs Perfect Continuous',
    country: 'Italy',
    template: 'Italy ___ struggling to qualify in recent years.',
    answer: 'has been',
    tense: 'present-perfect-continuous',
    fullSentence: 'Italy has been struggling to qualify in recent years.',
  },
  {
    id: 29,
    topic: 'Present Perfect vs Perfect Continuous',
    country: 'France',
    template: 'France ___ produced world-class players since 1998.',
    answer: 'has',
    tense: 'present-perfect',
    fullSentence: 'France has produced world-class players since 1998.',
  },
  {
    id: 30,
    topic: 'Present Perfect vs Perfect Continuous',
    country: 'Japan',
    template: 'Japan ___ growing its football league since 1993.',
    answer: 'has been',
    tense: 'present-perfect-continuous',
    fullSentence: 'Japan has been growing its football league since 1993.',
  },
  {
    id: 31,
    topic: 'Present Perfect vs Perfect Continuous',
    country: 'Morocco',
    template: 'Morocco ___ making history in recent cups.',
    answer: 'has been',
    tense: 'present-perfect-continuous',
    fullSentence: 'Morocco has been making history in recent cups.',
  },
  {
    id: 32,
    topic: 'Present Perfect vs Perfect Continuous',
    country: 'USA',
    template: 'The USA ___ developing football since 1994.',
    answer: 'has been',
    tense: 'present-perfect-continuous',
    fullSentence: 'The USA has been developing football since 1994.',
  },
  {
    id: 33,
    topic: 'Present Perfect vs Perfect Continuous',
    country: 'Spain',
    template: 'Spain ___ won three consecutive major trophies.',
    answer: 'has',
    tense: 'present-perfect',
    fullSentence: 'Spain has won three consecutive major trophies.',
  },
  {
    id: 34,
    topic: 'Present Perfect vs Perfect Continuous',
    country: 'Portugal',
    template: 'Portugal ___ playing in every cup since 2002.',
    answer: 'has been',
    tense: 'present-perfect-continuous',
    fullSentence: 'Portugal has been playing in every cup since 2002.',
  },
  {
    id: 35,
    topic: 'Present Perfect vs Perfect Continuous',
    country: 'England',
    template: 'England ___ hosted the World Cup once in 1966.',
    answer: 'has',
    tense: 'present-perfect',
    fullSentence: 'England has hosted the World Cup once in 1966.',
  },
  {
    id: 36,
    topic: 'Present Perfect vs Perfect Continuous',
    country: 'Netherlands',
    template: 'Netherlands ___ reaching finals without ever winning.',
    answer: 'has been',
    tense: 'present-perfect-continuous',
    fullSentence: 'Netherlands has been reaching finals without ever winning.',
  },

  // ─────────────────────────────────────────────────────────────
  // WILL VS GOING TO
  //   will        → spontaneous prediction / general future fact
  //   is going to → planned intention or evidence-based prediction
  // ─────────────────────────────────────────────────────────────
  {
    id: 37,
    topic: 'Will vs Going to',
    country: 'USA',
    template: 'The USA ___ host the 2026 World Cup.',
    answer: 'will',
    tense: 'will',
    fullSentence: 'The USA will host the 2026 World Cup.',
  },
  {
    id: 38,
    topic: 'Will vs Going to',
    country: 'Brazil',
    template: 'Brazil ___ aim for a sixth title in 2026.',
    answer: 'is going to',
    tense: 'going-to',
    fullSentence: 'Brazil is going to aim for a sixth title in 2026.',
  },
  {
    id: 39,
    topic: 'Will vs Going to',
    country: 'Canada',
    template: 'Canada ___ co-host the 2026 World Cup.',
    answer: 'will',
    tense: 'will',
    fullSentence: 'Canada will co-host the 2026 World Cup.',
  },
  {
    id: 40,
    topic: 'Will vs Going to',
    country: 'Mexico',
    template: 'Mexico ___ play at home stadiums in 2026.',
    answer: 'is going to',
    tense: 'going-to',
    fullSentence: 'Mexico is going to play at home stadiums in 2026.',
  },
  {
    id: 41,
    topic: 'Will vs Going to',
    country: 'Argentina',
    template: 'Argentina ___ face tough competition in 2026.',
    answer: 'will',
    tense: 'will',
    fullSentence: 'Argentina will face tough competition in 2026.',
  },
  {
    id: 42,
    topic: 'Will vs Going to',
    country: 'France',
    template: 'France ___ defend its 2018 title in 2026.',
    answer: 'is going to',
    tense: 'going-to',
    fullSentence: 'France is going to defend its 2018 title in 2026.',
  },
  {
    id: 43,
    topic: 'Will vs Going to',
    country: 'Germany',
    template: 'Germany ___ perform much better at the next cup.',
    answer: 'will',
    tense: 'will',
    fullSentence: 'Germany will perform much better at the next cup.',
  },
  {
    id: 44,
    topic: 'Will vs Going to',
    country: 'England',
    template: 'England ___ compete strongly for the 2026 title.',
    answer: 'is going to',
    tense: 'going-to',
    fullSentence: 'England is going to compete strongly for the 2026 title.',
  },
  {
    id: 45,
    topic: 'Will vs Going to',
    country: 'Morocco',
    template: 'Morocco ___ prove itself again in 2026.',
    answer: 'will',
    tense: 'will',
    fullSentence: 'Morocco will prove itself again in 2026.',
  },
  {
    id: 46,
    topic: 'Will vs Going to',
    country: 'Japan',
    template: 'Japan ___ surprise the football world in 2026.',
    answer: 'is going to',
    tense: 'going-to',
    fullSentence: 'Japan is going to surprise the football world in 2026.',
  },
  {
    id: 47,
    topic: 'Will vs Going to',
    country: 'Spain',
    template: 'Spain ___ bring young stars to the 2026 cup.',
    answer: 'will',
    tense: 'will',
    fullSentence: 'Spain will bring young stars to the 2026 cup.',
  },
  {
    id: 48,
    topic: 'Will vs Going to',
    country: 'Portugal',
    template: 'Portugal ___ build a new era after Ronaldo.',
    answer: 'is going to',
    tense: 'going-to',
    fullSentence: 'Portugal is going to build a new era after Ronaldo.',
  },

  // ─────────────────────────────────────────────────────────────
  // MIXED REVIEW
  // ─────────────────────────────────────────────────────────────
  {
    id: 49,
    topic: 'Mixed Review',
    country: 'Brazil',
    template: 'Brazil always ___ in World Cup tournaments.',
    answer: 'participates',
    tense: 'present-simple',
    fullSentence: 'Brazil always participates in World Cup tournaments.',
  },
  {
    id: 50,
    topic: 'Mixed Review',
    country: 'Germany',
    template: 'Germany ___ won the World Cup four times.',
    answer: 'has',
    tense: 'present-perfect',
    fullSentence: 'Germany has won the World Cup four times.',
  },
  {
    id: 51,
    topic: 'Mixed Review',
    country: 'Argentina',
    template: 'Argentina ___ the 2022 World Cup in Qatar.',
    answer: 'won',
    tense: 'past-simple',
    fullSentence: 'Argentina won the 2022 World Cup in Qatar.',
  },
  {
    id: 52,
    topic: 'Mixed Review',
    country: 'France',
    template: 'France ___ young talent for 2026 right now.',
    answer: 'is developing',
    tense: 'present-continuous',
    fullSentence: 'France is developing young talent for 2026 right now.',
  },
  {
    id: 53,
    topic: 'Mixed Review',
    country: 'Morocco',
    template: 'Morocco ___ making amazing history in recent cups.',
    answer: 'has been',
    tense: 'present-perfect-continuous',
    fullSentence: 'Morocco has been making amazing history in recent cups.',
  },
  {
    id: 54,
    topic: 'Mixed Review',
    country: 'Italy',
    template: 'Italy ___ not won the World Cup since 2006.',
    answer: 'has',
    tense: 'present-perfect',
    fullSentence: 'Italy has not won the World Cup since 2006.',
  },
  {
    id: 55,
    topic: 'Mixed Review',
    country: 'Spain',
    template: 'Spain ___ tiki-taka in every World Cup match.',
    answer: 'plays',
    tense: 'present-simple',
    fullSentence: 'Spain plays tiki-taka in every World Cup match.',
  },
  {
    id: 56,
    topic: 'Mixed Review',
    country: 'Japan',
    template: 'Japan ___ Europe in the 2022 World Cup.',
    answer: 'surprised',
    tense: 'past-simple',
    fullSentence: 'Japan surprised Europe in the 2022 World Cup.',
  },
  {
    id: 57,
    topic: 'Mixed Review',
    country: 'USA',
    template: 'The USA ___ developing football since 1994.',
    answer: 'has been',
    tense: 'present-perfect-continuous',
    fullSentence: 'The USA has been developing football since 1994.',
  },
  {
    id: 58,
    topic: 'Mixed Review',
    country: 'England',
    template: 'England ___ win the 2026 World Cup this time.',
    answer: 'will',
    tense: 'will',
    fullSentence: 'England will win the 2026 World Cup this time.',
  },
  {
    id: 59,
    topic: 'Mixed Review',
    country: 'Netherlands',
    template: 'Netherlands ___ reached three World Cup finals.',
    answer: 'has',
    tense: 'present-perfect',
    fullSentence: 'Netherlands has reached three World Cup finals.',
  },
  {
    id: 60,
    topic: 'Mixed Review',
    country: 'Croatia',
    template: 'Croatia ___ try for the semifinals in 2026.',
    answer: 'is going to',
    tense: 'going-to',
    fullSentence: 'Croatia is going to try for the semifinals in 2026.',
  },
]

// Helper: return all curiosities for a given topic.
// If topic is 'Random' or 'Mixed Review', returns the full set shuffled.
export function getCuriositiesForTopic(topic) {
  if (topic === 'Random') {
    return [...CURIOSITIES].sort(() => Math.random() - 0.5)
  }
  if (topic === 'Mixed Review') {
    return CURIOSITIES.filter(c => c.topic === 'Mixed Review')
      .sort(() => Math.random() - 0.5)
  }
  return CURIOSITIES.filter(c => c.topic === topic)
    .sort(() => Math.random() - 0.5)
}

// Helper: pick one curiosity for the given topic that matches one of the two
// selected countries. Falls back to any curiosity for that topic if no match.
export function pickCuriosity(topic, countryA, countryB) {
  const pool = getCuriositiesForTopic(topic)
  const matched = pool.filter(
    c => c.country === countryA || c.country === countryB,
  )
  const source = matched.length > 0 ? matched : pool
  return source[Math.floor(Math.random() * source.length)]
}
