export const SENTENCES = {
  'Present Simple vs Continuous': [
    { blank: 'She ___ to music right now.', hint: '(listen)', answer: 'is listening' },
    { blank: 'He ___ football every weekend.', hint: '(play)', answer: 'plays' },
    { blank: 'Water ___ at 100 degrees Celsius.', hint: '(boil)', answer: 'boils' },
    { blank: 'They ___ dinner at the moment.', hint: '(have)', answer: 'are having' },
    { blank: 'I usually ___ coffee in the morning.', hint: '(drink)', answer: 'drink' },
    { blank: 'Look! The cat ___ on the sofa.', hint: '(sleep)', answer: 'is sleeping' },
    { blank: 'She ___ as a teacher at this school.', hint: '(work)', answer: 'works' },
    { blank: 'We ___ a great time right now!', hint: '(have)', answer: "are having" },
    { blank: 'The sun ___ in the east every day.', hint: '(rise)', answer: 'rises' },
    { blank: 'He ___ on his laptop — do not disturb him.', hint: '(work)', answer: 'is working' },
  ],
  'Present Perfect vs Past Simple': [
    { blank: 'I ___ that film twice already.', hint: '(see)', answer: 'have seen' },
    { blank: 'She ___ to Paris last summer.', hint: '(travel)', answer: 'travelled' },
    { blank: 'He ___ his keys — he cannot find them.', hint: '(lose)', answer: 'has lost' },
    { blank: 'We ___ football yesterday afternoon.', hint: '(play)', answer: 'played' },
    { blank: 'They ___ here since 2015.', hint: '(live)', answer: 'have lived' },
    { blank: 'I ___ my homework an hour ago.', hint: '(finish)', answer: 'finished' },
    { blank: 'She ___ three cups of tea today.', hint: '(drink)', answer: 'has drunk' },
    { blank: 'He ___ the report before the meeting started.', hint: '(write)', answer: 'wrote' },
    { blank: 'I ___ never ___ sushi before tonight.', hint: '(eat)', answer: 'have … eaten' },
    { blank: 'They ___ a new stadium last year.', hint: '(build)', answer: 'built' },
  ],
  'Present Perfect vs Perfect Continuous': [
    { blank: 'I ___ this book all week and I love it.', hint: '(read)', answer: 'have been reading' },
    { blank: 'She ___ all the exercises — they are done.', hint: '(complete)', answer: 'has completed' },
    { blank: 'They ___ for the bus for 30 minutes.', hint: '(wait)', answer: 'have been waiting' },
    { blank: 'He ___ three emails so far this morning.', hint: '(send)', answer: 'has sent' },
    { blank: "I'm tired because I ___ all day.", hint: '(run)', answer: 'have been running' },
    { blank: 'She ___ English for five years.', hint: '(study)', answer: 'has been studying' },
    { blank: 'We ___ the whole pizza — nothing left!', hint: '(eat)', answer: 'have eaten' },
    { blank: 'It ___ since this morning — the streets are flooded.', hint: '(rain)', answer: 'has been raining' },
    { blank: 'He looks exhausted. He ___ all night.', hint: '(drive)', answer: 'has been driving' },
    { blank: 'The team ___ already ___ their strategy.', hint: '(decide)', answer: 'has … decided' },
  ],
  'Will vs Going to': [
    { blank: 'Look at those clouds — it ___ rain!', hint: '(will / going to)', answer: 'is going to' },
    { blank: 'I think Brazil ___ win the final.', hint: '(will / going to)', answer: 'will' },
    { blank: 'She already has her ticket — she ___ visit London.', hint: '(will / going to)', answer: 'is going to' },
    { blank: "Don't worry, I ___ help you with that.", hint: '(will / going to)', answer: 'will' },
    { blank: "They've booked the hotel — they ___ stay by the sea.", hint: '(will / going to)', answer: 'are going to' },
    { blank: 'I promise I ___ call you tomorrow.', hint: '(will / going to)', answer: 'will' },
    { blank: 'He feels dizzy — he ___ faint!', hint: '(will / going to)', answer: 'is going to' },
    { blank: 'Maybe I ___ try the new restaurant this weekend.', hint: '(will / going to)', answer: 'will' },
    { blank: "I've decided — I ___ study medicine.", hint: '(will / going to)', answer: "am going to" },
    { blank: 'Someone ___ answer the phone eventually.', hint: '(will / going to)', answer: 'will' },
  ],
  'Mixed Review': [
    { blank: 'She ___ right now, so call her later.', hint: '(sleep)', answer: 'is sleeping' },
    { blank: 'I ___ my wallet — I cannot pay!', hint: '(lose)', answer: 'have lost' },
    { blank: 'We ___ to the cinema last Friday.', hint: '(go)', answer: 'went' },
    { blank: 'He ___ English for three years.', hint: '(study)', answer: 'has been studying' },
    { blank: 'Look at the score — we ___ win!', hint: '(will / going to)', answer: 'are going to' },
    { blank: 'She usually ___ yoga on Sundays.', hint: '(do)', answer: 'does' },
    { blank: 'I promise I ___ be late again.', hint: "(won't / not going to)", answer: "won't" },
    { blank: 'They ___ this road last year.', hint: '(build)', answer: 'built' },
    { blank: 'He ___ already ___ dinner — the dishes are clean.', hint: '(make)', answer: 'has … made' },
    { blank: 'We ___ for the results since Monday.', hint: '(wait)', answer: 'have been waiting' },
  ],
}

export const ALL_TOPIC_KEYS = Object.keys(SENTENCES)
